version: '3.8'

networks:
  my_network:
    external:
      name: helpgrandelectronics_my-network

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: es-node01
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.security.enabled=$ELASTIC_SECURITY
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - my_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: kib-01
    ports:
      - "5601:5601"
    environment:  
     ELASTICSEARCH_HOSTS: '["http://es-node01:9200"]'  
    volumes:
    #  - ${PWD}/kibanaconfig:/usr/share/kibana/config/
     - ${PWD}/kibanaconfig:/tmp/kibana/config/
    #  - ./kibanaconfig/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - my_network

