version: "3"
services:
  nginx_ha:
    build: .
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - E:\devops\docker-basics\docker-haproxy\sites-enabled:/etc/nginx/site-enabled
    networks:
      my_network:
        aliases:
          - mywebapp
networks:
  my_network:
    external:
      name:  helpgrandelectronics_my-network



